"""Configuration for the candle-sequence LSTM experiment."""

SEQUENCE_LENGTH = 64
BATCH_SIZE = 128
HIDDEN_SIZE = 64
NUM_LAYERS = 1
DROPOUT = 0.1
LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-5
EPOCHS = 30
EARLY_STOPPING_PATIENCE = 8
MIN_EPOCHS_BEFORE_EARLY_STOP = 10
EARLY_STOPPING_MIN_DELTA = 5e-4
GRADIENT_CLIP = 1.0
VALIDATION_FRACTION = 0.15
MIN_TRAIN_ROWS = 200
MODEL_NAME = "lstm_candles_target"
PREDICTIONS_NAME = "lstm_candles_walk_forward_oos_predictions"

